# Dynamically generated by TF
export MODEL_BUCKET_PROD="mlflow-models-stg-mlops-zoomcamp"
export PREDICTIONS_STREAM_NAME="ride-predictions-stg-mlops-zoomcamp"
export LAMBDA_FUNCTION="stg_ride_prediction_lambda_mlops-zoomcamp"

# Model artifacts bucket from previous course work (MLflow experiments)
export MODEL_BUCKET_DEV="mlflow-models-magnus-dev"
export MLFLOW_EXPERIMENT_ID="2"
# Get latest RUN_ID from latest S3 partition.
# HACK, NOT FOR PRODUCTION!
# In practice, this is generally picked up from your experiment tracking tool such as MLflow or a DB
export RUN_ID=$(aws s3api list-objects-v2 \
    --bucket ${MODEL_BUCKET_DEV} \
    --query 'sort_by(Contents, &LastModified)[-1].Key' \
    --output=text | cut -f2 -d/)

# NOT FOR PRODUCTION
# Copy Model artifacts to newly created bucket
aws s3 sync s3://${MODEL_BUCKET_DEV} s3://${MODEL_BUCKET_PROD}

variables="{PREDICTIONS_STREAM_NAME=${PREDICTIONS_STREAM_NAME}, MODEL_BUCKET=${MODEL_BUCKET_PROD}, RUN_ID=${RUN_ID}, MLFLOW_EXPERIMENT_ID=${MLFLOW_EXPERIMENT_ID}}"

# https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html
aws lambda update-function-configuration --function-name ${LAMBDA_FUNCTION} --environment "Variables=${variables}"