{
 "title": "HW5 Evidently Dashboards",
 "time": { "from": "2024-02-29T08:29:16.855Z", "to": "2024-03-28T20:43:14.145Z" },
 "panels": [
  {
   "title": "Percentage of Missing Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT share_missing_values, \"timestamp\" FROM evidently_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT prediction_drift, \"timestamp\" FROM evidently_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Fare Amount Median",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT fare_amount_quantile, \"timestamp\" FROM evidently_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT num_drifted_columns, \"timestamp\" FROM evidently_metrics LIMIT 50 "
    }
   ]
  }
 ]
}