services:
  backend:
    image: ${LOCAL_IMAGE_NAME}
    ports:
      - 8080:8080
    environment:
      - PREDICTIONS_STREAM_NAME=${PREDICTIONS_STREAM_NAME}
      - RUN_ID=${RUN_ID}
      - TEST_RUN=False
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MODEL_LOCATION=/app/model
      - KINESIS_ENDPOINT_URL=http://kinesis:4566/
    volumes:
      - "./model:/app/model"

  kinesis:
    image: localstack/localstack:3.5.0
    ports:
      - 4566:4566
    environment:
      - SERVICES=kinesis